name: 'Release & Publish'
description: 'GitHub Action to release projects and publish packages'
author: 'godban'
inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  npm_token:
    description: 'Optional. If not provided, publishing to npm will be skipped. NPM token with publish permission.'
    required: false
  sources:
    description: 'Optional. Glob pattern. If not provided, publish will work against project root in single mode. Accepts glob pattern to work with multiple or other than root destinations.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: truck
  color: blue
